### ISSUE TITLE
build fails on 32 bit systems with -fPIC build flag 

### ISSUE THREAD

**Issue by selmf** [zeniko/unarr#2]
There's a bug in the version of lzma-sdk's CpuArch.c code used by unarr that makes building with -fPIC flag fail on 32 bit systems. An updated version of CpuArch.c is available from upstream:

http://sourceforge.net/p/sevenzip/bugs/1338/

Replacing CpuArch.c with this version works very nicely. Alternatively, you could also update lzmasdk to version 9.38 (which probably has some more bugfixes), but that might require a bit of more work.

If you're interested, I can also provide you with a patch for this issue.

**Comment by zeniko** [comment]
Thanks for the report. I've updated the lzmasdk code to version 9.38 with commit c4136ab9c9b07682d400158f5f933414df959e63.
